### ISSUE TITLE
There is no service configured with virtual machine <name> registered when starting botService.exe

### ISSUE THREAD

**Issue by spanditcaa** [microsoft/Broadcast-Development-Kit#38]
I've completed the configuration and installation of version 0.5.0-dev on azure, but get the error below when starting the bot service.  Note that the value of {{virtualMachineName}} at settings.BotConfiguration.virtualMachineName in environment.json is not included in the specification table at https://github.com/microsoft/Broadcast-Development-Kit/blob/c6867f75d6c655fbf09416411076b171a8ab43a4/docs/how-to-run-the-solution-in-azure/storage_account.md#placeholder-specification-table.  I have tried using the cname, azure VM name, the actual computername and get the same error.  What should the value be for this setting, and can you provide any other insight into this error?

Thank you.

```
C:\BotService-0.5.0-dev>BotService.exe --console
Is a Service False
[20:00:26 INF] Setting up database schema
[20:00:26 INF] Registering bot service
[20:00:26 INF] Instantiating CommunicationsClientBuilder for BotService
[20:00:26 INF] Instantiating AuthenticationProvider for BotService
[20:00:26 INF] Setting AuthenticationProvider for BotService
[20:00:26 INF] Setting NotificationUrl for BotService
[20:00:26 INF] Getting MediaPlatformSettings for BotService
[20:00:26 INF] Setting MediaPlatformSettings for BotService
[20:00:29 INF] Setting ServiceBaseUrl for BotService
[20:00:29 INF] Building Communication Client for BotService
[20:00:29 INF] Communication Client for BotService has been succesfully built
[20:00:30 ERR] [Bot Service API] There is no service configured with virtual machine teamsvideobroadcastvm registered

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Domain.Exceptions.EntityNotFoundException: [Bot Service API]There is no service configured with virtual machine teamsvideobroadcastvm registered
   at Application.Service.Commands.RegisterService.RegisterServiceCommandHandler.<Handle>d__3.MoveNext() in D:\Source\ms\Broadcast-Development-Kit\src\Application\Service\Commands\RegisterService.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Application.Common.ValidationBehaviour`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BotService.Infrastructure.Services.MediatorService.<RegisterServiceAsync>d__8.MoveNext() in D:\Source\ms\Broadcast-Development-Kit\src\BotService\Infrastructure\Services\MediatorService.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BotService.Infrastructure.Core.Bot.<RegisterServiceAsync>d__21.MoveNext() in D:\Source\ms\Broadcast-Development-Kit\src\BotService\Infrastructure\Core\Bot.cs:line 108
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at BotService.Infrastructure.Extensions.WebHostServiceExtensions.RegisterBotService(IWebHost host) in D:\Source\ms\Broadcast-Development-Kit\src\BotService\Infrastructure\Extensions\WebHostServiceExtensions.cs:line 40
   at BotService.Program.<Main>d__11.MoveNext() in D:\Source\ms\Broadcast-Development-Kit\src\BotService\Program.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BotService.Program.<Main>(String[] args)
   ```

**Comment by nithinbhargav** [comment]
@spanditcaa use the below API to register a service,

https://github.com/microsoft/Broadcast-Development-Kit/blob/main/docs/how-to-run-the-solution-in-azure/add_service.md#configureregister-the-service

**Comment by spanditcaa** [comment]
leaving this issue open as the docs aren't sequential - you hit this error before you get to the step to configure the service.  I'll PR when I have a chance.
